### ISSUE TITLE
can w3m customize style for a certain site separately

### ISSUE THREAD

**Issue by emacs25** [emacs-w3m/emacs-w3m#103]
for example, like this

w3m opens "www.google.com" then using a customized simple html template not css to render the site. 

is it possible to do it?

**Comment by Boruch-Baum** [comment]
On 2021-08-24 18:52, emacs25 wrote:
>    for example, like this
>
>    w3m opens "www.google.com" then using a customized simple html template
>    not css to render the site.
>
>    is it possible to do it?

Yes. Use the emacs-w3m "filter" feature to modify the html of any URL or
regex of URLs. emacs-w3m includes an entire elisp file called
w3m-filter.el  which is full of examples.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by emacs25** [comment]
thanks，I will have a try
