### ISSUE TITLE
mime-view package is not available in melpa install

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-w3m/emacs-w3m#108]
It seems that now APEL package is deprecated and unsafe to install.
But w3m still require mime-view which is part of APEL resulting in an error when compiling.
Even if this error which is here since ages now doesn't prevent using w3m, it is annoying, could you make a soft require of this library to prevent errors at compile time?

Thanks.

**Comment by yamaoka** [comment]
Only the shimbun library bundled with emacs-w3m uses APEL and FLIM packages, of which the development is still in progress along with Wanderlust.  Here they are:
https://github.com/wanderlust/apel
https://github.com/wanderlust/flim

**Comment by ncouture-invue** [comment]
Where can one find the mime-view library required by mime-w3m.el ?

To my surprise I was unable to find it, or any reference to it anywhere on the internet.

**Comment by yamaoka** [comment]
https://github.com/wanderlust/semi
mime-w3m.el is the module used for the SEMI package (containing the mime-view module) to enhance it to view html messages using emacs-w3m.　Currently the message program that uses SEMI is only Wanderlust, so you should not need to use mime-w3m.el unless you use Wanderlust (and those who use Wanderlust should know where SEMI is :-).

**Comment by thierryvolpiatto** [comment]
yamaoka ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> https://github.com/wanderlust/semi
> mime-w3m.el is the module used for the SEMI package (containing the mime-view module) to enhance it to view html messages using emacs-w3m.　Currently the message program that uses SEMI is
> only Wanderlust, so you should not need to use mime-w3m.el unless you use Wanderlust (and those who use Wanderlust should know where SEMI is :-).

Still, it is weird (and annoying) emacs-w3m requires it if not needed,
at least a soft require would be nice.

-- 
Thierry

**Comment by yamaoka** [comment]
> Still, it is weird (and annoying) emacs-w3m requires it if not needed,
> at least a soft require would be nice.

That is the right thing.　I'm going to make emacs-w3m error/warning
free when building (when I have time).

**Comment by thierryvolpiatto** [comment]
yamaoka ***@***.***> writes:

>     Still, it is weird (and annoying) emacs-w3m requires it if not needed,
>     at least a soft require would be nice.
>    
> That is the right thing.　I'm going to make emacs-w3m error/warning
> free when building (when I have time).

Great! And thanks for emacs-w3m!

-- 
Thierry
