### ISSUE TITLE
Package rfc2368 is deprecated

### ISSUE THREAD

**Issue by fintelkai** [emacs-w3m/emacs-w3m#109]
A few weeks ago, `rfc2368.el` was marked as obsolete: https://lists.gnu.org/archive/html/emacs-diffs/2021-08/msg00502.html. 

`emacs-w3m` loads `rfc2368` and emacs 28 emits "Package rfc2368 is deprecated".

**Comment by yamaoka** [comment]
Replaced with rfc6068.el.　Thanks.　Closing.

**Comment by fintelkai** [comment]
Cool, thanks for the quick solution.

**Comment by emacs-w3m-notifier** [comment]
i'm trying to find decent search engines that work with emacs-w3m.
wonding if anybody has ideas.

searx seems to sometimes not work -- at least the ones i have tried.
other ones might be reliable?  they list their engines.

some are only for onion though.  can w3m work decently with that?

startpage seems to dislike emacs-w3m for some reason, i think.
pr was it ixquic.  perhaps there are  others out there.

-- 
The Kafka Pandemic

Please learn what misopathy is.
https://thekafkapandemic.blogspot.com/2013/10/why-some-diseases-are-wronged.html

**Comment by jidanni** [comment]
I wish emacs would say when printing that warning,
what package is to blame.
People might get that warning,
without even having w3m  etc. installed,
but will google to this thread.
