### ISSUE TITLE
Wrong usage of aref in `w3m-form-p`

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-w3m/emacs-w3m#110]
Even if this function seems to be used nowhere in w3m, it is useful (I use it), `aref` is called with INDEX as first arg instead of ARRAY, here correct usage:

```elisp
(defun w3m-form-p (obj)
  "Return t if OBJ is a form object."
  (and (vectorp obj)
       (symbolp (aref obj 0))
       (eq (aref obj 0) 'w3m-form-object)))
```

**Comment by yamaoka** [comment]
Oops.  Thank you for fixing it.  Installed.
