### ISSUE TITLE
Any help on this, please? : `w3m.el package cl is deprecated` 

### ISSUE THREAD

**Issue by touxstone** [emacs-w3m/emacs-w3m#111]
Hi, group.
I am a user of `the 28.1 version of GNU/Emacs on Fedora 36` and starting to get the warning pasted below from the `Async-native-compile-log buffer`. Would anyone know to give a clue about what I should do to fix it, if so?
I would appreciate it.
````
w3m.el.gz:61:13: Warning: Package cl is deprecated
w3m.el.gz:150:14: Warning: autoload `w3m-toggle-filtering' docstring wider than 80 characters
/usr/share/emacs/site-lisp/w3m/w3m.el.gz: Error: Wrong type argument sequence
````

**Comment by yamaoka** [comment]
I guess w3m.el you are using is rather old, but the latest version of emacs-w3m is here (i.e., github), and it no longer loads cl directly.  See <https://emacs-w3m.github.io/> for the installation, please.

**Comment by touxstone** [comment]
> I guess w3m.el you are using is rather old, but the latest version of emacs-w3m is here (i.e., github), and it no longer loads cl directly. See https://emacs-w3m.github.io/ for the installation, please.

Thanks for your reply. Though I am using the `GNU/Emacs ver 28.1`, and as going on `Fedora 36` I have got installed the `emacs-w3m` `version 1.4.631-010.20180618cvs.fc36` officially packed at the current fedora repositories.

**Comment by yamaoka** [comment]
It seems to be that of 18 June 2018, that is, very old.　　IIRC, the Emacs version at that time was 26.3, and emacs-w3m officially supported 25 and 26, and of course 28 was not available yet.　　Emacs-w3m progresses day by day, so if you use a recent Emacs you are better to use a recent emacs-w3m.

**Comment by yamaoka** [comment]
Closing.
