### ISSUE TITLE
bookmark title bug

### ISSUE THREAD

**Issue by Boruch-Baum** [emacs-w3m/emacs-w3m#57]
Function w3m-bookmark-add-all-urls in file w3m-bookmark.el ~line 368
sets a variable title, but then doesn't use it. It should be used by
the call to the nearby function w3m-bookmark-write-file. There's no
need to use it in the nearby w3m-message since w3m-current-url is
already being displayed there.

I discovered this when working on PR #56, which needs to make other
changes to that function, so the fix is there. If you plan on merging
that PR, then when you do this issue can be closed; otherwise do you
want a separate PR just for this?

**Comment by yamaoka** [comment]
PR#56 fixed it.  Thanks.  Closing.
