### ISSUE TITLE
How to properly set w3m-display-mode?

### ISSUE THREAD

**Issue by valankar** [emacs-w3m/emacs-w3m#58]
Hello, I am using Spacemacs with this layer:

https://github.com/venmos/w3m-layer

I'm confused as to how to properly set w3m-display-mode at startup so it affects the first web page visited. Setting the variable does not do anything, and instead I need to M-x w3m-display-mode and select the mode before it takes effect. 

I tried something like the following in my config:

(setq w3m-display-mode "Plain")

**Comment by yamaoka** [comment]
There is not only the variable but also a command. 　 I think the author intended that a user to run `M-x w3m-display-mode RET` with completion. 　 Otherwise you can put this for example in the ~/.emacs-w3m.el file (not ~/.emacs):
(w3m-display-mode 'plain)

**Comment by valankar** [comment]
Thanks, I found this also works in ~/.emacs:

  (require 'w3m)
  (w3m-display-mode 'plain)
