### ISSUE TITLE
w3m causes (require 'ffap) to fail if ffap-url-regexp is nil

### ISSUE THREAD

**Issue by iwpiv** [emacs-w3m/emacs-w3m#59]
in `eval-after-load "ffap"` part in `w3m.el` file, a string matching is done without guarding against a nil value in `ffap-url-regexp`.

which by the variable documentation should be a legal value:
```
ffap-url-regexp is a variable defined in ‘ffap.el’.
Its value is nil

Regexp matching the beginning of a URI, for ffap.
If the value is nil, disable URL-matching features in ffap.
```

this will cause requiring ffap to fail, along with every function in emacs that depends on it.

**Comment by yamaoka** [comment]
Fixed in the git master.  Thanks.
