### ISSUE TITLE
wiki is closed for editing

### ISSUE THREAD

**Issue by Boruch-Baum** [emacs-w3m/emacs-w3m#6]
It may be that the wiki is set "Restrict editing to collaborators only", and so if I'm not listed as a collaborator on the "collaborators" tab of the "settings" page, I won't be able to contribute to the wiki.

Or it could be some other reason ...

My suggestion is to allow anyone to edit the wiki (ie. no restrictions). I don't see the privilege being abused on other wikis on github or on emacswiki ; any occassional abuse ought to be easy to revert; and if abuse does turn out to be a real issue, the restriction can always be re-imposed.

**Comment by tsuchm** [comment]
fixed
