### ISSUE TITLE
MELPA version w3m-20190709.548 breaks

### ISSUE THREAD

**Issue by peterwang** [emacs-w3m/emacs-w3m#61]
SPC runs the command w3m-scroll-up-or-next-url, which should scroll up the buffer, it now scrolls down the buffer.

**Comment by yamaoka** [comment]
Fixed.  Probably I did copy&yank that of scroll-down.  Thanks.

**Comment by yamaoka** [comment]
Sorry, that change did not fix it.  I found I broke the function definition for `w3m-scroll-up-or-next-url` wholly when dropping old Emacsen support.  Now it should really work.
