### ISSUE TITLE
Removed test on image-types in w3m-favicon  causes an error in 20190712

### ISSUE THREAD

**Issue by chipschap** [emacs-w3m/emacs-w3m#63]
Note: edited to clarify as my title may be misleading.

Possible regression: just prior to 20190712 the defcustom w3m-favicon-type (in w3-favicon.el) included a feature test for xemacs. The code looks to have been refactored and now image-types is referenced as a variable without a check. In a non-graphic environment image-types is undefined (at least, in my Termux setup, that's the case).

My temporary workaround in my startup code is, prior to setting up w3m, inserting a check for non-graphics environment and then setting image-types to nil.

**Comment by yamaoka** [comment]
Oh, I forgot `image-types' is not available on Emacs-noX.  Fixed in the git master.  Thanks.
