### ISSUE TITLE
Should `w3m-pop-up-windows` be marked as DEPRECATED?

### ISSUE THREAD

**Issue by larme** [emacs-w3m/emacs-w3m#68]
In recent versions of emacs-w3m, when I use functions like `w3m-search-new-session` or `w3m-goto-url-new-session`, w3m will pop up new windows even my `w3m-display-mode` is tabbed. 

It seems that `w3m-popup-window-p` only cares about `w3m-pop-up-windows` and its set to t. If it's the  correct behavior, should `w3m-pop-up-windows` be marked as DEPRECATED? Or should we change `w3m-popup-window-p` to respect the display mode?

**Comment by yamaoka** [comment]
Thank you for pointing it out.　I think I've fixed it.　Could you try the latest git master?

**Comment by larme** [comment]
That works for me. Thanks!

**Comment by yamaoka** [comment]
Thanks for verifying.　Closing.
