### ISSUE TITLE
w3m-create-page kills external process displaying external viewers

### ISSUE THREAD

**Issue by jaor** [emacs-w3m/emacs-w3m#69]
Hi.  When one tries to open a page that will invoke a external viewer via w3m-external-view called in w3m-create-page (say, a pdf for which my mailcap has an entry that calls a shell script that then calls emacsclent after doing other things), the external process is started and immediately w3m-process-stop is invoked on the page buffer (see w3m lines 6497-8). That call to w3m-process-stop kills the external viewer process and the display is thus abruptly aborted.

**Comment by yamaoka** [comment]
Confirmed.　I don't know why the author did put `w3m-process-stop` there in PR#55 (rev# 64e4626) but it is surely bad for a normal use case.　I've removed it.　Thank you for the report.

**Comment by jaor** [comment]
thanks a lot for the quick confirmation!
