### ISSUE TITLE
w3m-next/previous-anchor no more working in buffers formatted with w3m-region

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-w3m/emacs-w3m#71]
Hi,
Seems to happen since fecf209e53f177d5102f241abe846c43909f96a2.
I use w3m-region in mu4e buffers and w3m-next/previous-anchor returns "No anchor".
Thanks.

**Comment by yamaoka** [comment]
Hmm, I don't know how to reproduce it.　Could you attach a source that of before performing w3m-region?　(Or send it to <yamaoka(at)jpl.org>?)

**Comment by yamaoka** [comment]
I vaguely guess you are running `w3m-next-anchor` or `w3m-previous-anchor` in a buffer in which formatted web contents are copied from a temp buffer where `w3m-region` runs to format an html source.　If so, at least the local variable `w3m-max-anchor-sequence` should also be copied, for example:
```
(let (formatted-contents max-anchor)
  (set-buffer mu4e-buffer)
  (with-temp-buffer
    (insert an-html-contents)
    (w3m-region (point-min) (point-max))
    (setq formatted-contents (buffer-string)
          max-anchor w3m-max-anchor-sequence))
  (insert formatted-contents)
  (setq w3m-max-anchor-sequence max-anchor))
```

**Comment by thierryvolpiatto** [comment]
Thanks for your answer.

yamaoka <notifications@github.com> writes:

> I vaguely guess you are running w3m-next-anchor or w3m-previous-anchor
> in a buffer in which formatted web contents are copied from a temp
> buffer where w3m-region runs to format an html source.

Not exactly, here what I use:

    (setq mu4e-html2text-command (cond ((fboundp 'w3m)
                                        ;; Use emacs-w3m
                                        (lambda ()
                                          (w3m-region (point-min) (point-max))))
                                       ((executable-find "w3m")
                                        ;; Use w3m shell-command
                                        "w3m -T text/html")
                                       (t 'html2text)))

Then mu4e funcall this function.

I then use a command that use w3m-next-anchor:

    (defun tv/mu4e-next-anchor ()
      (interactive)
      (require 'w3m)
      (or (stringp (w3m-next-anchor))
          (let ((pos (point)))
            (when (eq (get-text-property (point) 'face)
                      'mu4e-link-face)
              (setq pos (next-single-property-change (point) 'face)))
            (let ((next-url (and pos
                                 (or (text-property-any
                                      pos (point-max)
                                      'face 'mu4e-link-face)
                                     (text-property-any
                                      (point-min) (point-max)
                                      'face 'mu4e-link-face)))))
              (and next-url (goto-char next-url))))))

Setting w3m-max-anchor-sequence at beginning of this function works.

> 　If so, at least the local variable w3m-max-anchor-sequence should
> also be copied, for example:
>
> (let (formatted-contents max-anchor)
>   (set-buffer mu4e-buffer)
>   (with-temp-buffer
>     (insert an-html-contents)
>     (w3m-region (point-min) (point-max))
>     (setq formatted-contents (buffer-string)
>           max-anchor w3m-max-anchor-sequence))
>   (insert formatted-contents)
>   (setq w3m-max-anchor-sequence max-anchor))

Hmm, I hardly see how this could work properly, w3m-max-anchor-sequence
would still remain to nil. Why don't you use make-local-variable instead
of make-variable-buffer-local? This would be much simpler, you could
give at beginning a reasonable default value and set it directly in each
w3m buffer when needed.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yamaoka** [comment]
```
(defun tv/mu4e-next-anchor ()
  (interactive)
  (require 'w3m)
  (or (stringp (w3m-next-anchor))
       ^^^^^^^
```
The return value of `w3m-next-anchor` does not have any mean anyway.　Ok, I'll look into the `mu4e` code and look for an suitable way to your function.　Give me time.

**Comment by yamaoka** [comment]
Please try the latest emacs-w3m and replacing
```
  (or (stringp (w3m-next-anchor))

with

  (or (w3m-next-anchor)
```
in your `tv/mu4e-next-anchor` function.

**Comment by thierryvolpiatto** [comment]
yamaoka <notifications@github.com> writes:

> Please try the latest emacs-w3m and replacing
>
>   (or (stringp (w3m-next-anchor))
>
> with
>
>   (or (w3m-next-anchor)
>
> in your tv/mu4e-next-anchor function.

Done but this is not enough, I have to give a default value to
`w3m-max-anchor-sequence` and then it is working.

    (defun tv/mu4e-next-anchor ()
      (interactive)
      (require 'w3m)
      (setq w3m-max-anchor-sequence 123)
      (or (w3m-next-anchor)
          (let ((pos (point)))
            (when (eq (get-text-property (point) 'face)
                      'mu4e-link-face)
              (setq pos (next-single-property-change (point) 'face)))
            (let ((next-url (and pos
                                 (or (text-property-any
                                      pos (point-max)
                                      'face 'mu4e-link-face)
                                     (text-property-any
                                      (point-min) (point-max)
                                      'face 'mu4e-link-face)))))
              (and next-url (goto-char next-url))))))
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yamaoka** [comment]
Ok.　After all I abolished the local variable `w3m-max-anchor-sequence` and changed `w3m-next-anchor` and the others so to work without it.　So, `w3m-max-anchor-sequence` is no longer needed to be set.　Please try the latest git master.

**Comment by thierryvolpiatto** [comment]
yamaoka <notifications@github.com> writes:

> Ok.　After all I abolished the local variable w3m-max-anchor-sequence
> and changed w3m-next-anchor and the others so to work without it.

Great.

> 　So, w3m-max-anchor-sequence is no longer needed to be set.　Please
> try the latest git master.

Thanks, working fine now.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yamaoka** [comment]
Thank you for verifying it!
