### ISSUE TITLE
w3m-content-type-alist takes ages to load in emacs-27

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-w3m/emacs-w3m#73]
This doesn't happen in emacs-26.3.

Thanks.

**Comment by yamaoka** [comment]
Confirmed.　In my Cygwin platform it can be doen in 0.38s to biuld the value for `w3m-content-type-alist` in 26.3.50, whereas it takes 1.38s in 27.0.50.　Though this is not so long, it should take more time if there are many entries in the system mailcap file(s) and user's one.　The program I tested it is: http://www.jpl.org/private/mailcap-test.el

The following change makes it shorter a little, though you will not probably be satisfied.
```
--- w3m.el~	2019-11-05 06:30:16.740395900 +0000
+++ w3m.el	2019-11-11 00:29:44.568986600 +0000
@@ -1180 +1180 @@
-	(setq viewer (mailcap-mime-info type))
+	(setq viewer (mailcap-mime-info type nil t))
```
In the first place, I think this is a fundamental problem of 27.0.50, not that of emacs-w3m, that is, it takes a long time to load mailcap.el and to parse mailcap files as follows:
```
emacs-26.3.50 -q -batch -eval PROG; emacs-27.0.50 -q -batch -eval PROG
0.0705951
0.2662782
```
Where "PROG" is:
```'(let ((start (current-time))) (require (quote mailcap)) (mailcap-parse-mailcaps) (mailcap-parse-mimetypes) (message "%s" (float-time (time-since start))))'```

Well, there is a way to make it very fast. 　That is, to copy the value of `w3m-content-type-alist` using `C-h v` after loading w3m.elc, and put this line in your Emacs init file (that should be read by Emacs before loading w3m.elc):
```(setq w3m-content-type-alist '((.................................................)))```

**Comment by thierryvolpiatto** [comment]
yamaoka <notifications@github.com> writes:

> Confirmed.　In my Cygwin platform it can be doen in 0.38s to biuld the value for w3m-content-type-alist in 26.3.50, whereas it takes 1.38s in 27.0.50.　Though this is
> not so long, it should take more time if there are many entries in the system mailcap file(s) and user's one.　The program I tested it is: 
> http://www.jpl.org/private/mailcap-test.el
>
> The following change makes it shorter a little, though you will not probably be satisfied.
>
> --- w3m.el~     2019-11-05 06:30:16.740395900 +0000
> +++ w3m.el      2019-11-11 00:29:44.568986600 +0000
> @@ -1180 +1180 @@
> -       (setq viewer (mailcap-mime-info type))
> +       (setq viewer (mailcap-mime-info type nil t))
>
> In the first place, I think this is a fundamental problem of 27.0.50, not that of emacs-w3m, that is, it takes a long time to load mailcap.el and to parse mailcap
> files as follows:
>
> emacs-26.3.50 -q -batch -eval PROG; emacs-27.0.50 -q -batch -eval PROG
> 0.0705951
> 0.2662782
>
> Where "PROG" is:
> '(let ((start (current-time))) (require (quote mailcap)) (mailcap-parse-mailcaps) (mailcap-parse-mimetypes) (message "%s" (float-time (time-since start))))'

Definitely a regression in emacs-27.

> Well, there is a way to make it very fast. 　That is, to copy the value of w3m-content-type-alist using C-h v after loading w3m.elc, and put this line in your Emacs
> init file (that should be read by Emacs before loading w3m.elc):
> (setq w3m-content-type-alist '((.................................................)))

Yes it's what I did.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yamaoka** [comment]
Ok.　I changed the way to update the value of `w3m-content-type-alist` so to do on demand instead of updating it fully according to `mailcap-mime-data` at the startup.　For example, the initial viewing method for the content-type "image/jpeg" is `(mailcap-mime-info "image/jpeg")` but when viewing a jpeg image for the first time, it will be replaced with `("real-viewer" file)`.　Could you try the latest git master?

**Comment by thierryvolpiatto** [comment]
yamaoka <notifications@github.com> writes:

> Ok.　I changed the way to update the value of w3m-content-type-alist
> so to do on demand instead of updating it fully according to
> mailcap-mime-data at the startup.　For example, the initial viewing
> method for the content-type "image/jpeg" is (mailcap-mime-info
> "image/jpeg") but when viewing a jpeg image for the first time, it
> will be replaced with ("real-viewer" file).　Could you try the latest
> git master?

I confirm it is now loading instantly :-)

Great, thank you.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yamaoka** [comment]
On Mon, 11 Nov 2019 00:54:55 -0800, Thierry Volpiatto wrote:
> I confirm it is now loading instantly :-)
> Great, thank you.

You're welcome.　Closing.
