### ISSUE TITLE
w3m-redisplay-pages-automatically hook interferes with exwm

### ISSUE THREAD

**Issue by jaor** [emacs-w3m/emacs-w3m#75]
Right now, `w3m-mode` unconditionally adds `w3m-redisplay-pages-automatically` to `window-configuration-hook` (incidentally, doing this every time w3m-mode is called seems redundant, and makes harder than it should removing the hook).   It would be nice if this were configurable: there're circumstances where i don't want w3m to redisplay (or try to) behind my back, and the logic of that hook is a bit convoluted.  As an example, exwm is picky in how it handles focus and layouts, and that w3m hook interferes with the final focus of windows; while that's not necessarily w3m's fault (exwm layout handler should be most robust), it be nice to be able to customize out this interference :)

Thanks!

**Comment by yamaoka** [comment]
Ok.　I added a new user option `w3m-redisplay-pages-automatically-p'.　Try setting it to nil (t by default).
