### ISSUE TITLE
Repeated same img tags are packed

### ISSUE THREAD

**Issue by ikazuhiro** [emacs-w3m/emacs-w3m#76]
When `img` tags which have the same `src` parameter are repeated without any characters, only one image is displayed.

```html
<img src="image.jpg"><img src="image.jpg>
```

If there is a SPACE between tags, two images are displayed.
```html
<img src="image.jpg"> <img src="image.jpg>
```

**Comment by yamaoka** [comment]
Fixed in master.  Thanks.
Hope this change does not enbug other kinds. ;)

**Comment by ikazuhiro** [comment]
Thank you for your response.  As far as I tested,
1. It seems that Cygwin's w3m.exe is probably too old to output `hseq` parameters.  I needed to build w3m myself.
2. `t` (`w3m-toggle-inline-image`) at the beginning of the second image anchor toggles two consecutive images on.
3. `t` toggles all same images off.

**Comment by yamaoka** [comment]
> 1 It seems that Cygwin's w3m.exe is probably too old to output hseq
>  parameters. I needed to build w3m myself.

In my Cygwin box /usr/bin/w3m.exe is w3m/0.5.3.　Oh, it always returns only the help page no matter what command line options emacs-w3m issues.　I normally use /usr/local/bin/w3m.exe built from the latest source gotten from `https://salsa.debian.org/debian/w3m.git/` .

> 2 t (w3m-toggle-inline-image) at the beginning of the second image
>  anchor toggles two consecutive images on.
> 3 t toggles all same images off.

Fixed.　Thank you for pointing these out.

**Comment by ikazuhiro** [comment]
All problems were fixed with my locally built w3m binary.  Thank you.
