### ISSUE TITLE
Reformat after each text zoom

### ISSUE THREAD

**Issue by jidanni** [emacs-w3m/emacs-w3m#90]
$ gunzip [f.htm.gz](https://github.com/emacs-w3m/emacs-w3m/files/6167751/f.htm.gz)
$ emacs -q --eval '(w3m "f.htm")'
c-x c-+ c-+ ...

The table should be reformatted.
Instead words start going off the screen.

R (w3m-reload-this-page) doesn't help.

emacs-w3m-version "1.4.632"

**Comment by jidanni** [comment]
Maybe
https://github.com/emacs-w3m/emacs-w3m/commit/051dba16c2d60e7b59143ed5c1d52bceca3b6b37
fixes it. I don't know. I am waiting for it to arrive at Debian sid...

**Comment by Boruch-Baum** [comment]
On 2021-03-18 16:49, 積丹尼 Dan Jacobson wrote:
>    Maybe
>    [1]051dba1
>    fixes it. I don't know. I am waiting for it to arrive at Debian sid...

That commit version is available via MELPA, so if your you set-up allows
for MELPA use, you could check that, and in the process get benefits of
any other commits not in the debian package.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
