### ISSUE TITLE
Specify http_proxy and https_proxy at the same time.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-w3m/emacs-w3m#91]
On Ubuntu 20.04, I try to use emacs-w3m within the self compiled git master version of Emacs.  The `emacs-w3m` document told the following for proxy setting:
```
     (setq w3m-command-arguments
           (nconc w3m-command-arguments
                  '("-o" "http_proxy=http://proxy.hogege.com:8000/")))
```
But I want to set the `http_proxy` and `https_proxy` variables at the same time and tried with the following settings in `~/.emacs-w3m.el`:
```
     (setq w3m-command-arguments
           (nconc w3m-command-arguments
                  '(
                  ("-o" "http_proxy=http://127.0.0.1:8000/")
                  ("-o" "https_proxy=http://127.0.0.1:8000/")
                  )
                  ))
```
It seems that the above settings doesn't work at all. Any hints will be highly appreciated.

Regards,
HY

**Comment by emacs-w3m-notifier** [comment]
On 2021-04-06 02:04, hongyi-zhao wrote:
>    The document told the following for proxy setting:
>      (setq w3m-command-arguments
>            (nconc w3m-command-arguments
>                   '("-o" "http_proxy=http://proxy.hogege.com:8000/")))
>
>    But how can I set the http_proxy and https_proxy variables at the same
>    time?

Have you tried this?

      (setq w3m-command-arguments
            (nconc w3m-command-arguments
                   '("-o" "http_proxy=http://proxy.hogege.com:8000/")
                   '("-o" "https_proxy=https://............:....../")))


--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by hongyi-zhao** [comment]
Thanks a lot. Based on hour notes, I use the following, and it really does the trick:
```
      (setq w3m-command-arguments
            (nconc w3m-command-arguments
                   '("-o" "http_proxy=http://127.0.0.1:8080/")
                   '("-o" "https_proxy=http://127.0.0.1:8080/")))
```
Regards,
HY

**Comment by Boruch-Baum** [comment]
Good to hear. If you're happy with the solution, please close the issue (I can't do that).
